name: .NET with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      MSBUILDDISABLENODEREUSE: 1
      MSBuildEnableWorkloadResolver: false
      DOTNET_HOST_ARCH: x64
      DOTNET_ROOT: C:\Program Files\dotnet\

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add dotnet tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Start SonarCloud Analysis
        run: dotnet-sonarscanner begin /k:"Jassiel-13_PesoIdeal" /o:"repositorio-3-0" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build Solution
        run: dotnet build "P7U1 - Peso Ideal/P7U1 - Peso Ideal.sln" --configuration Release --runtime win-x64

      - name: End SonarCloud Analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
