name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Paso 1: Hacer checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar el SDK de .NET
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.203'

      # Paso 3: Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore "P7U1 - Peso Ideal/P7U1 - Peso Ideal.sln"

      # Paso 4: Construir el proyecto
      - name: Build with .NET
        run: dotnet build "P7U1 - Peso Ideal/P7U1 - Peso Ideal.sln" --configuration Release

      # Paso 5: Configurar SonarCloud y ejecutar el an치lisis (begin)
      - name: Run SonarCloud Analysis - Begin
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"Jassiel-13_PesoIdeal" /o:"repositorio-3-0" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"

      # Paso 6: Ejecutar pruebas
      - name: Run Tests
        run: dotnet test "P7U1 - Peso Ideal/P7U1 - Peso Ideal.sln"

      # Paso 7: Ejecutar el an치lisis de SonarCloud (end)
      - name: Run SonarCloud Analysis - End
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      # Paso 8: Publicar los artefactos de la construcci칩n
      - name: Publish Build Artifacts
        run: |
          dotnet publish "P7U1 - Peso Ideal/P7U1 - Peso Ideal.sln" --configuration Release --output publish
